### ISSUE TITLE
README.md file | Partially obsolete content

### ISSUE THREAD

**Issue by Ricky-Tigg** [wchen342/ungoogled-chromium-fedora#27]
Hello. Some information in the README.md file became obsolete.
- CentOS as such was discontinued, thus regardless the version.
- No download source at https://build.opensuse.org/project/show/home:ungoogled_chromium
- Non-existent entry for this application in repository for applications in RPM format at https://download.opensuse.org/repositories/home:/ungoogled_chromium/

Remaining valid information
- Availability of this application on Flathub
- [not in position to determine] _Building_ section.

**Comment by PF4Public** [comment]
As you may see this repository is barely maintained

**Comment by Ricky-Tigg** [comment]
Nothing that can't be fixed then.

**Comment by PF4Public** [comment]
Anyone willing to maintain is welcome

**Comment by Ricky-Tigg** [comment]
As usual in a desperate case, it is appropriate to close.
